### ISSUE TITLE
Have router.start() return promise

### ISSUE THREAD

**Issue by aaronshaf** [thetalecrafter/middle-router#11]
It would be nice for terse testing if router.start() returned a promise that completed upon first-route resolve.

```
window.location.hash = '/tos'
await router.start()
```

**Comment by thetalecrafter** [comment]
I think that might be nice.

**Comment by thetalecrafter** [comment]
Currently `start()` returns `this`, so a change would be a major version change. It also only addresses the convenience of the first time routing.

What if instead there was a `router.routing` promise that refers to the current route completion promise. While it isn't routing, it would be `null`. What do you think?

**Comment by aaronshaf** [comment]
I don't see value in `start()` returning this. Chaining would happening earlier (.get, .post, etc).

Terse testing win:

```javascript
await router.start({url})
// check stuff
router.stop()
```
