### ISSUE TITLE
Feature request: start() takes argument of first navigation route

### ISSUE THREAD

**Issue by aaronshaf** [thetalecrafter/middle-router#17]
`router.start(url: string)`

or

`router.start({url: string})`

Would make for more terse testing.

**Comment by thetalecrafter** [comment]
If no url is passed in, should it default to routing the current location as it does now?
Should it replace the current url, or navigate?

**Comment by aaronshaf** [comment]
If url empty: current location

If url filled: navigate

My bias here is testing. There might be a better way to do it (for example, depending entirely on changing location.href directly). Hashing complicates things.

**Comment by thetalecrafter** [comment]
I think it may be nice to decouple listening for changes and the first routing. `2.0.0` added some nice ways to handle navigating, perhaps I should add a `listen()` method that begins listening, but doesn't route the current location. That way a test could setup listeners before, and stop afterwards. What do you think?

**Comment by thetalecrafter** [comment]
This issue is quite stale. If there is another suggestion for the ideal api for testing, please reopen.
