### ISSUE TITLE
Params is empty inside a middleware not added on a route .use

### ISSUE THREAD

**Issue by shichongrui** [thetalecrafter/middle-router#21]
the params object should be filled for middleware that are not on a route. For example

    router
      .use(someMiddleware) // in this middleware params is empty
      .use('/:id', routeHandler) // in this handler params has the id

Ideally all middleware should have the params regardless of where it lies in the use structure.

**Comment by thetalecrafter** [comment]
Parameters are determined when the path is matched. The url cannot been matched against all of the possible patterns in all nested routes before running any middleware.
