### ISSUE TITLE
Feature: ability to cancel exiting of route

### ISSUE THREAD

**Issue by aaronshaf** [thetalecrafter/middle-router#4]

**Comment by aaronshaf** [comment]
Yes, but would be nice if the listener add/remove was automatic.

**Comment by thetalecrafter** [comment]
So it automatically removed all beforeexit handlers when an exit is not prevented?

**Comment by aaronshaf** [comment]
Yes. Perhaps:

```javascript
router.use(async function({ router, exiting, beforeExit }) {
  beforeExit(async function () { /* resolve to continue, reject to cancel? */ })
  await exiting
})
```

**Comment by thetalecrafter** [comment]
I think the decision to prompt or not must be synchronous, since this would be used in `beforeunload`, as well as on link clicks.
