### ISSUE TITLE
UMD Support

### ISSUE THREAD

**Issue by jimsimon** [thetalecrafter/middle-router#68]
It'd be great if this library used UMD so apps that don't use a module loader can use it too (i.e. Polymer apps).

**Comment by thetalecrafter** [comment]
I haven't set up a UMD build before, so a pull request would be helpful.

**Comment by jimsimon** [comment]
This probably isn't an issue anymore since the only large framework I know of that doesn't support module loaders (Polymer) is going to in their next release.
